### ISSUE TITLE
ERROR_VALUE_INVALID on sandbox /api/v2_1/orders request

### ISSUE THREAD

**Issue by improf** [PayU-EMEA/plugin_magento_24#28]
### General
Test was done on sandbox mode.

Magento:
"magento/product-community-edition": "2.4.6-p3"

PayU Plugin:
"payu/magento24-payment-gateway": "2.0.1"

### Issue
When we are trying to place order on sandbox mode environment with PayU credit cards method, we are receiving the following error:
`ERROR_VALUE_INVALID - OPENPAYU_PAYMENT_CREATE_ERROR_OTHER_TEMPORARY`

This error is not available on the list provided by PayU, so we don't know how to solve it - https://developers.payu.com/europe/pl/docs/payouts/payouts-api/error-codes/.

### More info
We have checked the body that we are sending on this request - it seems to be correct.
`{"order":{"description":"Zamówienie 123 [....com]","customerIp":"127.0.0.1","extOrderId":"123_65cb204f03b4f","notifyUrl":"https://.../pl/payu/data/getNotify/type/payu_gateway_card/store/1/","continueUrl":"https://.../pl/checkout/onepage/success/","totalAmount":"16189","currencyCode":"PLN","merchantPosId":"341496","payMethods":{"payMethod":{"type":"CARD_TOKEN","value":"TOKD_1LHRVR0MQNQS02z9zw3J4HjUWjF"}},"buyer":{"email":"abc@abc.net","firstName":"Iza","lastName":"Test","phone":"435434543","extCustomerId":"48344","language":"pl","delivery":{"street":"Szkolna 21","postalCode":"41-500","city":"Bytom","countryCode":"PL"}},"products":[{"quantity":1.0,"name":"Golf","unitPrice":"14990"},{"quantity":1,"name":"Shipment [Kurier DPD]","unitPrice":"1199"}],"threeDsAuthentication":{"cardholder":{"name":"Iza Test","billingAddress":{"countryCode":"PL","street":"Szkolna 21","city":"Bytom","postalCode":"41-500"}},"browser":{"requestIP":"127.0.0.1","screenWidth":"","javaEnabled":"","timezoneOffset":"","screenHeight":"","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","colorDepth":"","language":""}}}}`

Could you explain us what `ERROR_VALUE_INVALID - OPENPAYU_PAYMENT_CREATE_ERROR_OTHER_TEMPORARY` error mean?

**Comment by regdos** [comment]
Are you sure you are using plugin version 2.0.1? All requests from POS 341496 appear as 2.0.0. 
Probably The problem is `"quantity":1.0,` but this has just been fixed in 2.0.1

**Comment by improf** [comment]
You're right. We have just upgraded plugin to version 2.0.1 but we still have the same error.

The example of full error below:
`[2024-02-13T12:03:53.203961+00:00] payULogger.CRITICAL: ERROR_VALUE_INVALID - OPENPAYU_PAYMENT_CREATE_ERROR_OTHER_TEMPORARY {"order":{"description":"Zamówienie S1110495274 [test...com]","customerIp":"127.0.0.1","extOrderId":"S1110495274_65cb5aa8a451e","notifyUrl":"https://test.....com/pl/payu/data/getNotify/type/payu_gateway_card/store/1/","continueUrl":"https://test.....com/pl/checkout/onepage/success/","totalAmount":"16189","currencyCode":"PLN","merchantPosId":"341496","payMethods":{"payMethod":{"type":"CARD_TOKEN","value":"TOKD_1LHRVS5MKLRS4qJi7s01JtqaF4m"}},"buyer":{"email":"abc@abc.net","firstName":"Iza","lastName":"Test","phone":"435434543","extCustomerId":"48344","language":"pl","delivery":{"street":"Szkolna 21","postalCode":"41-500","city":"Bytom","countryCode":"PL"}},"products":[{"quantity":1,"name":"Golf","unitPrice":"14990"},{"quantity":1,"name":"Shipment [Kurier DPD]","unitPrice":"1199"}],"threeDsAuthentication":{"cardholder":{"name":"Iza Test","billingAddress":{"countryCode":"PL","street":"Szkolna 21","city":"Bytom","postalCode":"41-500"}},"browser":{"requestIP":"127.0.0.1","screenWidth":"","javaEnabled":"","timezoneOffset":"","screenHeight":"","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","colorDepth":"","language":""}}}} []`

Could you check this again?

**Comment by regdos** [comment]
`Token has expired`. Please contact with PayU Support - https://poland.support.payu.com/
